name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: datachainlab/rust-cache@allow_registry_src_caching
        with:
          workspaces: |
            .
            ./enclave
          cache-directories: |
            ~/.cargo/registry/src/**/librocksdb-sys-*
      - run: make lint-tools
      - run: make lint

  sdk-test:
    runs-on: ubuntu-22.04
    env:
      SGX_MODE: SW
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - uses: datachainlab/rust-cache@allow_registry_src_caching
        with:
          workspaces: |
            .
            ./enclave
          cache-directories: |
            ~/.cargo/registry/src/**/librocksdb-sys-*
      - run: curl -LO https://download.01.org/intel-sgx/sgx-linux/2.23/distro/ubuntu22.04-server/sgx_linux_x64_sdk_2.23.100.2.bin 
      - run: chmod +x ./sgx_linux_x64_sdk_2.23.100.2.bin
      - run: echo -e 'no\n/opt' | ./sgx_linux_x64_sdk_2.23.100.2.bin
      - run: source /opt/sgxsdk/environment && make -B
      - run: source /opt/sgxsdk/environment && make test
      - run: source /opt/sgxsdk/environment && make integration-test
